#Workflow to deploy sphinx documentation to github pages

name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Build documentation
        id: build-docs
        run: |
          sphinx-build -M html docs/source docs/build

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.build-docs.outputs.artifact }}
 